apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: {{ include "devops-playground.namespace" . }}

spec:
  type: {{ .Values.postgres.service.type }}

  selector:
    app: {{ include "devops-playground.postgresLabel" . }}

  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}