apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.postgres.persistence.name }}
  namespace: {{ include "devops-playground.namespace" . }}

spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}

  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}

  storageClassName: {{ .Values.postgres.persistence.storageClass }}