apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: {{ include "devops-playground.namespace" . }}

type: Opaque

data:
  POSTGRES_USER: {{ .Values.secret.postgres.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.password | b64enc }}

---

apiVersion: v1
kind: Secret

metadata:
  name: devops-api-secret
  namespace: {{ include "devops-playground.namespace" . }}

type: Opaque

data:
  DB_USERNAME: {{ .Values.secret.api.username | b64enc }}
  DB_PASSWORD: {{ .Values.secret.api.password | b64enc }}