apiVersion: v1
kind: ConfigMap

metadata:
  name: api-config
  namespace: devops-playground

data:
  ASPNETCORE_ENVIRONMENT: "Development"

  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=devopsplayground;Username=postgres;Password=postgres"

  ASPNETCORE_URLS: "http://+:8080"